#!/bin/bash
# Author Andrey Sorokin aka shadow_alone

# table ip filter {
# 	set $REALLISTNAME {
# 		type ipv4_addr
# 	}
# }


#Set path for ipset and ipsetd
IPNFT="/usr/sbin/nft"
IPDIG="/usr/bin/dig"
IPGREP="/usr/bin/grep"

# Add domain-name
MyDomains="rg.andrey.org"

MyIP=`$IPDIG +short $MyDomains | $IPGREP -v "\.$"`

REALLISTNAME=$1
[ -z "$1" ] && REALLISTNAME="home-rg-ip"

$IPNFT get element ip filter $REALLISTNAME { $MyIP }

if [ $? -ne 0 ]; then
	$IPNFT flush set filter $REALLISTNAME
	$IPNFT add element ip filter $REALLISTNAME { $MyIP }
fi
